"""
Complete list of all moves available in Generation 1 of Pokémon (Red/Blue/Yellow).
This includes all 165 moves from the original Generation 1 games.
"""

from dataclasses import dataclass
from typing import Optional, List
from src.state.pokestate_defs import Target, Type, Move, Category, PokemonEffect

# All Generation 1 moves (165 total)
GEN1_MOVES = [
    # Normal-type moves
    Move(
        "Bite",
        Type.NORMAL,
        60,
        Category.PHYSICAL,
        100,
        40,
        "Bites with sharp fangs. May cause flinching.",
    ),
    Move(
        "Pound",
        Type.NORMAL,
        40,
        Category.PHYSICAL,
        100,
        56,
        "A basic attack with a low power.",
    ),
    Move(
        "Karate Chop",
        Type.NORMAL,
        50,
        Category.PHYSICAL,
        100,
        40,
        "A chopping attack with a high critical-hit ratio.",
    ),
    Move(
        "Double Slap",
        Type.NORMAL,
        15,
        Category.PHYSICAL,
        85,
        16,
        "Hits 2-5 times in one turn.",
    ),
    Move(
        "Comet Punch",
        Type.NORMAL,
        18,
        Category.PHYSICAL,
        85,
        24,
        "Hits 2-5 times in one turn.",
    ),
    Move(
        "Fire Punch",
        Type.FIRE,
        75,
        Category.PHYSICAL,
        100,
        24,
        "A fiery punch. May cause a burn.",
    ),
    Move(
        "Thunder Punch",
        Type.ELECTRIC,
        75,
        Category.PHYSICAL,
        100,
        24,
        "An electric punch. May cause paralysis.",
    ),
    Move(
        "Ice Punch",
        Type.ICE,
        75,
        Category.PHYSICAL,
        100,
        24,
        "An icy punch. May cause freezing.",
    ),
    Move(
        "Vine Whip",
        Type.GRASS,
        18,
        Category.PHYSICAL,
        100,
        35,
        "A Grass-type attack. The Pokémon uses its cruel whips to strike the opponent.",
    ),
    Move("Mega Punch", Type.NORMAL, 80, Category.PHYSICAL, 85, 32, "A powerful punch."),
    Move(
        "Pay Day",
        Type.NORMAL,
        40,
        Category.PHYSICAL,
        100,
        32,
        "Scatters coins that are picked up after battle.",
    ),
    Move(
        "Scratch",
        Type.NORMAL,
        40,
        Category.PHYSICAL,
        100,
        56,
        "Scratches with sharp claws.",
    ),
    Move(
        "Vice Grip",
        Type.NORMAL,
        55,
        Category.PHYSICAL,
        100,
        48,
        "Grips with powerful pincers.",
    ),
    Move(
        "Guillotine",
        Type.NORMAL,
        None,
        Category.PHYSICAL,
        30,
        8,
        "A one-hit KO attack.",
    ),
    Move(
        "Razor Wind",
        Type.NORMAL,
        80,
        Category.SPECIAL,
        100,
        16,
        "A two-turn attack with high critical-hit ratio.",
    ),
    Move(
        "Swords Dance",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        48,
        "Sharply raises Attack.",
    ),
    Move(
        "Cut", Type.NORMAL, 50, Category.PHYSICAL, 95, 48, "Cuts with claws or blades."
    ),
    Move(
        "Gust",
        Type.NORMAL,
        40,
        Category.SPECIAL,
        100,
        56,
        "Strikes with a gust of wind.",
    ),
    Move(
        "Wing Attack",
        Type.FLYING,
        60,
        Category.PHYSICAL,
        100,
        56,
        "Strikes with wings.",
    ),
    Move(
        "Whirlwind",
        Type.NORMAL,
        None,
        Category.STATUS,
        85,
        32,
        "Blows away the foe and ends the battle.",
    ),
    Move(
        "Fly",
        Type.FLYING,
        70,
        Category.PHYSICAL,
        95,
        24,
        "Flies high on the first turn, attacks on the second.",
    ),
    Move(
        "Bind",
        Type.NORMAL,
        15,
        Category.PHYSICAL,
        85,
        32,
        "Binds the target for 4-5 turns.",
    ),
    Move(
        "Slam",
        Type.NORMAL,
        80,
        Category.PHYSICAL,
        75,
        32,
        "Slams the foe with a tail or vine.",
    ),
    Move(
        "Stomp",
        Type.NORMAL,
        65,
        Category.PHYSICAL,
        100,
        32,
        "Stomps with a big foot. May cause flinching.",
    ),
    Move(
        "Double Kick",
        Type.FIGHTING,
        30,
        Category.PHYSICAL,
        100,
        48,
        "Kicks twice in one turn.",
    ),
    Move("Mega Kick", Type.NORMAL, 120, Category.PHYSICAL, 75, 8, "A powerful kick."),
    Move(
        "Jump Kick",
        Type.FIGHTING,
        70,
        Category.PHYSICAL,
        95,
        40,
        "A jumping kick. If it misses, the user is hurt.",
    ),
    Move(
        "Rolling Kick",
        Type.FIGHTING,
        60,
        Category.PHYSICAL,
        85,
        24,
        "A fast kick delivered from a rapid spin.",
    ),
    Move(
        "Sand-Attack",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        24,
        "Reduces the foe's accuracy.",
    ),
    Move(
        "Headbutt",
        Type.NORMAL,
        70,
        Category.PHYSICAL,
        100,
        24,
        "A ramming attack. May cause flinching.",
    ),
    Move(
        "Horn Attack", Type.NORMAL, 65, Category.PHYSICAL, 100, 40, "Stabs with a horn."
    ),
    Move(
        "Fury Attack",
        Type.NORMAL,
        15,
        Category.PHYSICAL,
        85,
        32,
        "Hits 2-5 times in one turn.",
    ),
    Move(
        "Horn Drill",
        Type.NORMAL,
        None,
        Category.PHYSICAL,
        30,
        8,
        "A one-hit KO attack.",
    ),
    Move(
        "Tackle",
        Type.NORMAL,
        35,
        Category.PHYSICAL,
        95,
        56,
        "A full-body charge attack.",
    ),
    Move(
        "Body Slam",
        Type.NORMAL,
        85,
        Category.PHYSICAL,
        100,
        24,
        "A full-body slam. May cause paralysis.",
    ),
    Move(
        "Wrap",
        Type.NORMAL,
        15,
        Category.PHYSICAL,
        90,
        32,
        "Wraps around the foe for 4-5 turns.",
    ),
    Move(
        "Take Down",
        Type.NORMAL,
        90,
        Category.PHYSICAL,
        85,
        32,
        "A reckless tackle that also hurts the user.",
    ),
    Move(
        "Thrash",
        Type.NORMAL,
        90,
        Category.PHYSICAL,
        100,
        32,
        "A rampage that lasts 2-3 turns.",
    ),
    Move(
        "Double-Edge",
        Type.NORMAL,
        120,
        Category.PHYSICAL,
        100,
        24,
        "A reckless tackle that also hurts the user.",
    ),
    Move(
        "Tail Whip",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        48,
        "Lowers the foe's Defense.",
        target_effects=[PokemonEffect("defense", "-1")],
    ),
    Move(
        "Leer",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        48,
        "Lowers the foe's Defense.",
        target_effects=[PokemonEffect("defense", "-1")],
    ),
    Move(
        "Growl",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        64,
        "Lowers the foe's Attack.",
        target_effects=[PokemonEffect("attack", "-1")],
    ),
    Move(
        "Roar",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        32,
        "Scares the foe away and ends the battle.",
    ),
    Move(
        "Sing",
        Type.NORMAL,
        None,
        Category.STATUS,
        55,
        24,
        "A soothing song that puts the foe to sleep.",
    ),
    Move(
        "Supersonic",
        Type.NORMAL,
        None,
        Category.STATUS,
        55,
        32,
        "Confuses the foe with an ultrasonic sound.",
    ),
    Move(
        "Sonic Boom",
        Type.NORMAL,
        None,
        Category.SPECIAL,
        90,
        32,
        "Always inflicts 20 HP damage.",
    ),
    Move(
        "Disable",
        Type.NORMAL,
        None,
        Category.STATUS,
        80,
        32,
        "Disables one of the foe's moves.",
    ),
    Move(
        "Acid",
        Type.POISON,
        40,
        Category.SPECIAL,
        100,
        48,
        "Sprays acid. May lower Defense.",
    ),
    Move(
        "Ember",
        Type.FIRE,
        40,
        Category.SPECIAL,
        100,
        40,
        "A small flame. May cause a burn.",
    ),
    Move(
        "Flamethrower",
        Type.FIRE,
        95,
        Category.SPECIAL,
        100,
        24,
        "A powerful fire attack. May cause a burn.",
    ),
    Move("Mist", Type.ICE, None, Category.STATUS, 100, 48, "Prevents stat reduction."),
    Move(
        "Water Gun",
        Type.WATER,
        40,
        Category.SPECIAL,
        100,
        40,
        "Squirts water to attack.",
    ),
    Move(
        "Hydro Pump",
        Type.WATER,
        120,
        Category.SPECIAL,
        80,
        8,
        "A powerful water attack.",
    ),
    Move(
        "Surf",
        Type.WATER,
        95,
        Category.SPECIAL,
        100,
        24,
        "A big wave that strikes all Pokémon.",
    ),
    Move(
        "Ice Beam",
        Type.ICE,
        95,
        Category.SPECIAL,
        100,
        16,
        "An icy attack. May cause freezing.",
    ),
    Move(
        "Blizzard",
        Type.ICE,
        120,
        Category.SPECIAL,
        90,
        8,
        "A howling blizzard. May cause freezing.",
    ),
    Move(
        "Psybeam",
        Type.PSYCHIC,
        65,
        Category.SPECIAL,
        100,
        32,
        "A psychic attack. May cause confusion.",
    ),
    Move(
        "Bubble Beam",
        Type.WATER,
        65,
        Category.SPECIAL,
        100,
        32,
        "Fires bubbles. May lower Speed.",
    ),
    Move(
        "Aurora Beam",
        Type.ICE,
        65,
        Category.SPECIAL,
        100,
        32,
        "A rainbow beam. May lower Attack.",
    ),
    Move(
        "Hyper Beam",
        Type.NORMAL,
        150,
        Category.SPECIAL,
        90,
        8,
        "Powerful, but leaves the user immobile the next turn.",
    ),
    Move(
        "Peck",
        Type.FLYING,
        35,
        Category.PHYSICAL,
        100,
        56,
        "Attacks with a beak or horn.",
    ),
    Move(
        "Drill Peck",
        Type.FLYING,
        80,
        Category.PHYSICAL,
        100,
        32,
        "A corkscrewing attack with the beak.",
    ),
    Move(
        "Submission",
        Type.FIGHTING,
        80,
        Category.PHYSICAL,
        80,
        40,
        "A reckless tackle that also hurts the user.",
    ),
    Move(
        "Low Kick",
        Type.FIGHTING,
        50,
        Category.PHYSICAL,
        90,
        32,
        "A low kick that trips the foe.",
    ),
    Move(
        "Counter",
        Type.FIGHTING,
        None,
        Category.PHYSICAL,
        100,
        32,
        "Returns a physical attack double.",
    ),
    Move(
        "Seismic Toss",
        Type.FIGHTING,
        None,
        Category.PHYSICAL,
        100,
        32,
        "Inflicts damage equal to the user's level.",
    ),
    Move(
        "Strength",
        Type.NORMAL,
        80,
        Category.PHYSICAL,
        100,
        24,
        "A powerful physical attack.",
    ),
    Move(
        "Absorb",
        Type.GRASS,
        20,
        Category.SPECIAL,
        100,
        40,
        "An attack that steals half the damage inflicted.",
    ),
    Move(
        "Mega Drain",
        Type.GRASS,
        40,
        Category.SPECIAL,
        100,
        24,
        "An attack that steals half the damage inflicted.",
    ),
    Move(
        "Leech Seed",
        Type.GRASS,
        None,
        Category.STATUS,
        90,
        16,
        "Plants a seed that steals HP every turn.",
    ),
    Move(
        "Growth",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        64,
        "Raises Attack and Special Attack.",
        target=Target.SELF,
        target_effects=[PokemonEffect("special_attack", "+1")],
    ),
    Move(
        "Razor Leaf",
        Type.GRASS,
        55,
        Category.PHYSICAL,
        95,
        40,
        "Cuts with leaves. High critical-hit ratio.",
    ),
    Move(
        "Solarbeam",
        Type.GRASS,
        120,
        Category.SPECIAL,
        100,
        16,
        "Absorbs light on turn 1, attacks on turn 2.",
    ),
    Move(
        "Poison Powder",
        Type.POISON,
        None,
        Category.STATUS,
        75,
        56,
        "Scatters poison powder.",
        target_effects=[PokemonEffect("status", "POISON")],
    ),
    Move(
        "Stun Spore",
        Type.GRASS,
        None,
        Category.STATUS,
        75,
        48,
        "Scatters paralysis powder.",
        target_effects=[PokemonEffect("status", "PARALYZED")],
    ),
    Move(
        "Sleep Powder",
        Type.GRASS,
        None,
        Category.STATUS,
        75,
        24,
        "Scatters sleep powder.",
        target_effects=[PokemonEffect("status", "SLEEP")],
    ),
    Move(
        "Petal Dance",
        Type.GRASS,
        70,
        Category.SPECIAL,
        100,
        32,
        "A rampage that lasts 2-3 turns.",
    ),
    Move(
        "String Shot",
        Type.BUG,
        None,
        Category.STATUS,
        95,
        64,
        "Lowers the foe's Speed.",
    ),
    Move(
        "Dragon Rage",
        Type.DRAGON,
        None,
        Category.SPECIAL,
        100,
        16,
        "Always inflicts 40 HP damage.",
    ),
    Move(
        "Fire Spin",
        Type.FIRE,
        15,
        Category.SPECIAL,
        70,
        24,
        "Traps the foe in fire for 4-5 turns.",
    ),
    Move(
        "Thunder Shock",
        Type.ELECTRIC,
        40,
        Category.SPECIAL,
        100,
        48,
        "An electric attack. May cause paralysis.",
    ),
    Move(
        "Thunderbolt",
        Type.ELECTRIC,
        95,
        Category.SPECIAL,
        100,
        24,
        "A powerful electric attack. May cause paralysis.",
    ),
    Move(
        "Thunder Wave",
        Type.ELECTRIC,
        None,
        Category.STATUS,
        100,
        32,
        "Paralyzes with electricity.",
        target_effects=[PokemonEffect("status", "PARALYZED")],
    ),
    Move(
        "Thunder",
        Type.ELECTRIC,
        120,
        Category.SPECIAL,
        70,
        16,
        "A lightning attack. May cause paralysis.",
    ),
    Move(
        "Rock Throw",
        Type.ROCK,
        50,
        Category.PHYSICAL,
        90,
        24,
        "Throws rocks at the foe.",
    ),
    Move(
        "Earthquake",
        Type.GROUND,
        100,
        Category.PHYSICAL,
        100,
        16,
        "An earthquake that strikes all Pokémon.",
    ),
    Move(
        "Fissure", Type.GROUND, None, Category.PHYSICAL, 30, 8, "A one-hit KO attack."
    ),
    Move(
        "Dig",
        Type.GROUND,
        60,
        Category.PHYSICAL,
        100,
        16,
        "Digs underground on turn 1, attacks on turn 2.",
    ),
    Move(
        "Toxic",
        Type.POISON,
        None,
        Category.STATUS,
        85,
        16,
        "Poisons the foe with an intensifying toxin.",
    ),
    Move(
        "Confusion",
        Type.PSYCHIC,
        50,
        Category.SPECIAL,
        100,
        40,
        "A psychic attack. May cause confusion.",
    ),
    Move(
        "Psychic",
        Type.PSYCHIC,
        90,
        Category.SPECIAL,
        100,
        16,
        "A powerful psychic attack. May lower Special Defense.",
    ),
    Move(
        "Hypnosis",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        60,
        32,
        "A hypnotic move that puts the foe to sleep.",
    ),
    Move("Meditate", Type.PSYCHIC, None, Category.STATUS, 100, 64, "Raises Attack."),
    Move(
        "Agility", Type.PSYCHIC, None, Category.STATUS, 100, 48, "Sharply raises Speed."
    ),
    Move(
        "Quick Attack",
        Type.NORMAL,
        40,
        Category.PHYSICAL,
        100,
        48,
        "An extremely fast attack that always strikes first.",
        priority=1,
    ),
    Move(
        "Rage", Type.NORMAL, 20, Category.PHYSICAL, 100, 32, "Raises Attack when hit."
    ),
    Move(
        "Teleport",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        100,
        32,
        "Warps away from battle.",
    ),
    Move(
        "Night Shade",
        Type.GHOST,
        None,
        Category.SPECIAL,
        100,
        24,
        "Inflicts damage equal to the user's level.",
    ),
    Move(
        "Mimic",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        16,
        "Copies a move used by the foe.",
    ),
    Move(
        "Screech",
        Type.NORMAL,
        None,
        Category.STATUS,
        85,
        64,
        "Sharply lowers the foe's Defense.",
    ),
    Move(
        "Double Team",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        24,
        "Creates illusory copies to raise evasiveness.",
    ),
    Move(
        "Recover",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        32,
        "Restores HP by half the max HP.",
    ),
    Move("Harden", Type.NORMAL, None, Category.STATUS, 100, 48, "Raises Defense."),
    Move(
        "Minimize",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        32,
        "Sharply raises evasiveness.",
    ),
    Move(
        "Smokescreen",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        32,
        "Lowers the foe's accuracy.",
    ),
    Move(
        "Confuse Ray", Type.GHOST, None, Category.STATUS, 100, 16, "Confuses the foe."
    ),
    Move(
        "Withdraw",
        Type.WATER,
        None,
        Category.STATUS,
        100,
        64,
        "Raises Defense.",
        target=Target.SELF,
        target_effects=[PokemonEffect("defense", "+1")],
    ),
    Move(
        "Defense Curl",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        64,
        "Raises Defense.",
        target=Target.SELF,
        target_effects=[PokemonEffect("defense", "+1")],
    ),
    Move(
        "Barrier",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        100,
        48,
        "Sharply raises Special Defense.",
    ),
    Move(
        "Light Screen",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        100,
        48,
        "Reduces damage from special attacks.",
    ),
    Move("Haze", Type.ICE, None, Category.STATUS, 100, 48, "Resets all stat changes."),
    Move(
        "Reflect",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        100,
        32,
        "Reduces damage from physical attacks.",
    ),
    Move(
        "Focus Energy",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        48,
        "Raises the critical-hit ratio.",
    ),
    Move(
        "Bide",
        Type.NORMAL,
        None,
        Category.PHYSICAL,
        100,
        16,
        "Endures attacks for 2 turns, then strikes back double.",
    ),
    Move(
        "Metronome",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        16,
        "Randomly uses any move.",
    ),
    Move(
        "Mirror Move",
        Type.FLYING,
        None,
        Category.STATUS,
        100,
        32,
        "Counters with the same move.",
    ),
    Move(
        "Selfdestruct",
        Type.NORMAL,
        200,
        Category.PHYSICAL,
        100,
        8,
        "Inflicts severe damage but makes the user faint.",
    ),
    Move(
        "Egg Bomb",
        Type.NORMAL,
        100,
        Category.PHYSICAL,
        75,
        16,
        "An egg is hurled at the foe.",
    ),
    Move(
        "Lick",
        Type.GHOST,
        20,
        Category.PHYSICAL,
        100,
        48,
        "Licks with a long tongue. May cause paralysis.",
    ),
    Move(
        "Smog",
        Type.POISON,
        20,
        Category.SPECIAL,
        70,
        32,
        "An attack that may poison the foe.",
    ),
    Move(
        "Sludge",
        Type.POISON,
        65,
        Category.SPECIAL,
        100,
        32,
        "Hurls sludge. May poison the foe.",
    ),
    Move(
        "Bone Club",
        Type.GROUND,
        65,
        Category.PHYSICAL,
        85,
        32,
        "Clubs the foe with a bone.",
    ),
    Move(
        "Fire Blast",
        Type.FIRE,
        120,
        Category.SPECIAL,
        85,
        8,
        "A fiery blast that may inflict a burn.",
    ),
    Move(
        "Waterfall",
        Type.WATER,
        80,
        Category.PHYSICAL,
        100,
        24,
        "Charges with a waterfall.",
    ),
    Move(
        "Clamp",
        Type.WATER,
        35,
        Category.PHYSICAL,
        85,
        24,
        "Clamps the foe for 4-5 turns.",
    ),
    Move(
        "Swift",
        Type.NORMAL,
        60,
        Category.SPECIAL,
        100,
        32,
        "Fires stars that never miss.",
    ),
    Move(
        "Skull Bash",
        Type.NORMAL,
        100,
        Category.PHYSICAL,
        100,
        24,
        "Raises Defense on turn 1, attacks on turn 2.",
    ),
    Move(
        "Spike Cannon",
        Type.NORMAL,
        20,
        Category.PHYSICAL,
        100,
        24,
        "Fires spikes that hit 2-5 times.",
    ),
    Move(
        "Constrict",
        Type.NORMAL,
        10,
        Category.PHYSICAL,
        100,
        56,
        "Constricts to attack. May lower Speed.",
    ),
    Move(
        "Amnesia",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        100,
        32,
        "Sharply raises Special Defense.",
    ),
    Move(
        "Kinesis",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        80,
        24,
        "Lowers the foe's accuracy.",
    ),
    Move(
        "Softboiled",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        16,
        "Restores HP by half the max HP.",
    ),
    Move(
        "High Jump Kick",
        Type.FIGHTING,
        85,
        Category.PHYSICAL,
        90,
        32,
        "A jumping kick. If it misses, the user is hurt.",
    ),
    Move("Glare", Type.NORMAL, None, Category.STATUS, 75, 48, "Paralyzes the foe."),
    Move(
        "Dream Eater",
        Type.PSYCHIC,
        100,
        Category.SPECIAL,
        100,
        24,
        "Eats the dreams of a sleeping foe.",
    ),
    Move("Poison Gas", Type.POISON, None, Category.STATUS, 55, 64, "Poisons the foe."),
    Move(
        "Barrage",
        Type.NORMAL,
        15,
        Category.PHYSICAL,
        85,
        32,
        "Hurls round objects. Hits 2-5 times.",
    ),
    Move(
        "Leech Life",
        Type.BUG,
        20,
        Category.PHYSICAL,
        100,
        24,
        "An attack that steals half the damage inflicted.",
    ),
    Move(
        "Lovely Kiss",
        Type.NORMAL,
        None,
        Category.STATUS,
        75,
        16,
        "Demands a kiss with a scary face. May cause sleep.",
    ),
    Move(
        "Sky Attack",
        Type.FLYING,
        140,
        Category.PHYSICAL,
        90,
        8,
        "Charges on turn 1, attacks on turn 2.",
    ),
    Move(
        "Transform",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        16,
        "Transforms into the foe.",
    ),
    Move(
        "Bubble",
        Type.WATER,
        20,
        Category.SPECIAL,
        100,
        48,
        "Fires bubbles. May lower Speed.",
    ),
    Move(
        "Dizzy Punch",
        Type.NORMAL,
        70,
        Category.PHYSICAL,
        100,
        16,
        "A rhythmic punch. May cause confusion.",
    ),
    Move(
        "Spore",
        Type.GRASS,
        None,
        Category.STATUS,
        100,
        24,
        "Scatters spores that always induce sleep.",
    ),
    Move(
        "Flash",
        Type.NORMAL,
        None,
        Category.STATUS,
        70,
        32,
        "Looses a powerful flash. Lowers accuracy.",
    ),
    Move(
        "Psywave",
        Type.PSYCHIC,
        None,
        Category.SPECIAL,
        80,
        24,
        "Attacks with a psychic wave of varying intensity.",
    ),
    Move(
        "Splash",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        64,
        "It's just a splash... Has no effect whatsoever.",
    ),
    Move(
        "Acid Armor",
        Type.POISON,
        None,
        Category.STATUS,
        100,
        64,
        "Sharply raises Defense.",
    ),
    Move(
        "Crabhammer",
        Type.WATER,
        90,
        Category.PHYSICAL,
        90,
        16,
        "Hammers with a claw. High critical-hit ratio.",
    ),
    Move(
        "Explosion",
        Type.NORMAL,
        250,
        Category.PHYSICAL,
        100,
        8,
        "Inflicts severe damage but makes the user faint.",
    ),
    Move(
        "Fury Swipes",
        Type.NORMAL,
        18,
        Category.PHYSICAL,
        80,
        24,
        "Rakes with claws. Hits 2-5 times.",
    ),
    Move(
        "Bonemerang",
        Type.GROUND,
        50,
        Category.PHYSICAL,
        90,
        16,
        "Hurls a bone that hits twice.",
    ),
    Move(
        "Rest",
        Type.PSYCHIC,
        None,
        Category.STATUS,
        100,
        16,
        "The user sleeps for 2 turns, restoring HP and status.",
    ),
    Move(
        "Rock Slide",
        Type.ROCK,
        75,
        Category.PHYSICAL,
        90,
        16,
        "Large rocks are hurled. May cause flinching.",
    ),
    Move(
        "Hyper Fang",
        Type.NORMAL,
        80,
        Category.PHYSICAL,
        90,
        24,
        "Attacks with sharp fangs. May cause flinching.",
    ),
    Move("Sharpen", Type.NORMAL, None, Category.STATUS, 100, 48, "Raises Attack."),
    Move(
        "Conversion",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        48,
        "Changes type to that of the top move.",
    ),
    Move(
        "Tri Attack",
        Type.NORMAL,
        80,
        Category.SPECIAL,
        100,
        16,
        "Fires three types of beams simultaneously.",
    ),
    Move(
        "Super Fang",
        Type.NORMAL,
        None,
        Category.PHYSICAL,
        90,
        16,
        "Attacks with sharp fangs and cuts HP in half.",
    ),
    Move(
        "Slash",
        Type.NORMAL,
        70,
        Category.PHYSICAL,
        100,
        32,
        "Slashes with claws. High critical-hit ratio.",
    ),
    Move(
        "Substitute",
        Type.NORMAL,
        None,
        Category.STATUS,
        100,
        16,
        "Creates a decoy using 1/4 of max HP.",
    ),
    Move(
        "Twinneedle",
        Type.BUG,
        25,
        Category.PHYSICAL,
        100,
        24,
        "Hits twice in one turn with bug-like needles.",
    ),
]

# Move categories (since Gen 1 didn't have explicit categories, these are based on typical usage)
HIGH_POWER_MOVES = [move for move in GEN1_MOVES if move.power and move.power >= 100]
MEDIUM_POWER_MOVES = [
    move for move in GEN1_MOVES if move.power and 50 <= move.power < 100
]
LOW_POWER_MOVES = [move for move in GEN1_MOVES if move.power and move.power < 50]

# One-hit KO moves
OHKO_MOVES = [
    move for move in GEN1_MOVES if move.name in ["Guillotine", "Horn Drill", "Fissure"]
]

# Multi-hit moves
MULTI_HIT_MOVES = [
    move
    for move in GEN1_MOVES
    if move.name
    in [
        "Double Slap",
        "Comet Punch",
        "Fury Attack",
        "Double Kick",
        "Spike Cannon",
        "Barrage",
        "Fury Swipes",
        "Bonemerang",
    ]
]

# Two-turn moves
TWO_TURN_MOVES = [
    move
    for move in GEN1_MOVES
    if move.name
    in ["Razor Wind", "Fly", "Solarbeam", "Skull Bash", "Sky Attack", "Dig"]
]

TRAPPING_MOVES = [
    move for move in GEN1_MOVES if move.name in ["Wrap", "Fire Spin", "Bind", "Clamp"]
]


def get_moves_by_type(type_name: str) -> List[Move]:
    """Get all moves of a specific type."""
    return [move for move in GEN1_MOVES if move.type == type_name]


def get_moves_by_power_range(min_power: int, max_power: int) -> List[Move]:
    """Get all moves within a power range."""
    return [
        move
        for move in GEN1_MOVES
        if move.power and min_power <= move.power <= max_power
    ]


def print_move_summary():
    """Print a summary of all Generation 1 moves."""
    print("Generation 1 Pokémon Moves Summary")
    print("=" * 40)
    print(f"Total moves: {len(GEN1_MOVES)}")
    print(f"High power moves (100+): {len(HIGH_POWER_MOVES)}")
    print(f"Medium power moves (50-99): {len(MEDIUM_POWER_MOVES)}")
    print(f"Low power moves (<50): {len(LOW_POWER_MOVES)}")
    print(f"One-hit KO moves: {len(OHKO_MOVES)}")
    print(f"Multi-hit moves: {len(MULTI_HIT_MOVES)}")
    print(f"Two-turn moves: {len(TWO_TURN_MOVES)}")
